# Generated by Django 2.1.1 on 2018-12-05 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0017_task_vending'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='kodik',
            field=models.CharField(default='dd', max_length=500),
        ),
        migrations.AddField(
            model_name='task',
            name='owner',
            field=models.CharField(default='dd', max_length=500),
        ),
        migrations.AddField(
            model_name='zakaz',
            name='kartinka',
            field=models.CharField(default='url', max_length=100),
        ),
    ]
